[changelog]
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^perf", group = "performance" },
    { message = "^refactor", group = "refactor" },
    { message = "^security", group = "security" },
    { message = "^chore|^build|^ci|^style|^test", skip = true },
    { message = "^.*", group = "other" },
]

[[package]]
name = "clorinde"
changelog_include = ["codegen_template"]
changelog_path = "CHANGELOG.md"
